nics:
  enp37s0:  # ifname
    vlan:
      5:  # vlan id
        ipv4: 10.2.0.1/24  # Proper CIDR
        maps:
          # skb prio : vlan pri
          2: 2
          3: 3
      10:
        ipv4: null  # Optional. Can be removed
        maps:
          2: 2
          3: 3  # For perf test
    tas:
      txtime_delay: 500000
      schedule:
        - time: 300us
          prio: [ 5 ]
        - time: 300000ns
          prio: [ 2, 3 ]
        - time: 400000
          prio: [ -1 ]
    cbs:
      # prio: dict map
      3:
        class: a
        max_frame: 512B
        bandwidth: 70000kbps
      2:
        class: b
        max_frame: 512B
        bandwidth: 30Mbps
