name: Build

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install clang-format
        run: sudo apt install -qqy --no-install-recommends clang-format
      - name: Run clang-format
        run: bin/check-clang-format
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Flake8
        uses: py-actions/flake8@v1
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master

  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-18.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: install build tools
        run: sudo apt install -qqy --no-install-recommends gcc cmake ninja-build
      - name: Checkout
        uses: actions/checkout@master
      - name: Install js dependencies
        run: yarn --cwd dashboard install
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Setup poetry
        uses: Gr1n/setup-poetry@v7
      - name: Install python dependencies
        run: |
          poetry config --local virtualenvs.in-project true
          poetry install
      - name: build
        run: |
          mkdir build && cd build
          /usr/bin/cmake -G Ninja -DBUILD_EXAMPLES=ON ..
          /usr/bin/cmake --build .
