name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy_deb:
    runs-on: ubuntu-latest
    environment: deploy
    env:
      REPO_HOST: ${{ secrets.REPO_HOST }}
      REPO_USER: ${{ secrets.REPO_USER }}
      REPO_PATH: ${{ secrets.REPO_PATH }}
      REPO_PORT: ${{ secrets.REPO_PORT }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: install build tools
        run: sudo apt install -qqy --no-install-recommends git-buildpackage

      - name: Checkout
        uses: actions/checkout@master

      - name: Install requirements
        run: sudo apt install -qqy --no-install-recommends git-buildpackage

      - name: setup-deploy
        run: .ci/setup.sh

      - name: Generate changelogs
        run: .ci/changelog.sh

      - name: build-deb
        id: build
        uses: tsnlab/build-dpkg-buster@master
        with:
          args: --unsigned-source --unsigned-changes

      - name: deploy
        run: |
          scp ${{ steps.build.outputs.filename }} packages:$REPO_PATH/tmp/
          ssh packages reprepro -b $REPO_PATH includedeb unstable $REPO_PATH/tmp/${{ steps.build.outputs.filename }}
          ssh packages rm $REPO_PATH/tmp/${{ steps.build.outputs.filename }}
